apiVersion: v1
kind: Service
metadata:
  name: translate-app-service
spec:
  selector:
    app: translate-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # Or NodePort for local testing
